version: '3.8'

services:

  db:
    container_name: pg_imdb
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: wasp
      POSTGRES_PASSWORD: root
      POSTGRES_DB: imdb
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_imdb
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: krtkabna@gmail.com
      PGADMIN_DEFAULT_PASSWORD: PGAdmin
    ports:
      - "5050:80"
